import {Pagination} from '../common/Pagination';
import {usePagedResource} from '../../hooks/usePagedResource';
import React,{useEffect,useRef,useState} from 'react';
import {api,apiFetch} from '../../services/api';
import {Lesson,subjects,control,button,panel} from './learning';
import {LessonView} from './LessonView';

type Question={questionText:string;options:string[];correctOptionIndex:number;explanation:string};
const initial=()=>({title:'',description:'',subject:'Physics',stream:'Both',topic:'',topicOrder:1,lessonOrder:1,estimatedMinutes:15,medium:'English',syllabus:'current',status:'draft'});
export const AdminCourseManager:React.FC=()=>{

  const [form,setForm]=useState(initial),[editing,setEditing]=useState<Lesson|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const [videos,setVideos]=useState<{title:string;url:string}[]>([]),[files,setFiles]=useState<File[]>([]),[resources,setResources]=useState<NonNullable<Lesson['resources']>>([]);
  const [quiz,setQuiz]=useState<Question[]>([]),[related,setRelated]=useState<string[]>([]),[preview,setPreview]=useState<Lesson|null>(null),[fileKey,setFileKey]=useState(0);
  const [search,setSearch]=useState(''),[filterSubject,setFilterSubject]=useState(''),[filterStatus,setFilterStatus]=useState('');
  const lessonsPage=usePagedResource<Lesson>('/courses/admin/list','courses',{q:search,subject:filterSubject,status:filterStatus},'mindmaze_courses_updated');
  const [paperSearch,setPaperSearch]=useState(''),[selectedPapersOnly,setSelectedPapersOnly]=useState(false);
  const [topicChoices,setTopicChoices]=useState<{subject:string;topic:string;topicOrder:number}[]>([]);
  useEffect(()=>{let cancelled=false;const loadTopics=()=>apiFetch('/courses/admin/topics').then(r=>{if(!cancelled)setTopicChoices(r.topics);}).catch(()=>{});loadTopics();window.addEventListener('mindmaze_courses_updated',loadTopics);return()=>{cancelled=true;window.removeEventListener('mindmaze_courses_updated',loadTopics);};},[]);
  const papersPage=usePagedResource<any>('/past-papers','papers',selectedPapersOnly?{ids:related.join(','),q:paperSearch}:{subject:form.subject,q:paperSearch},'mindmaze_papers_updated');
  const lessons=lessonsPage.items,papers=papersPage.items,loading=lessonsPage.loading;
  const load=lessonsPage.reload;
  const reset=()=>{setForm(initial());setEditing(null);setVideos([]);setFiles([]);setResources([]);setQuiz([]);setRelated([]);setFileKey(k=>k+1);setError('');};
  const edit=(lesson:Lesson)=>{
    setEditing(lesson);setForm({title:lesson.title,description:lesson.description,subject:lesson.subject,stream:lesson.stream,topic:lesson.topic,topicOrder:lesson.topicOrder,lessonOrder:lesson.lessonOrder,estimatedMinutes:lesson.estimatedMinutes,medium:lesson.medium,syllabus:lesson.syllabus,status:lesson.status});
    setVideos((lesson.videos||[]).map(v=>({...v})));setResources(lesson.resources||[]);setFiles([]);setQuiz((lesson.quiz||[]).map(q=>({...q,options:[...q.options],correctOptionIndex:q.correctOptionIndex??0,explanation:q.explanation||''})));setRelated(lesson.relatedPaperIds||[]);setFileKey(k=>k+1);setError('');setMessage('');
    document.getElementById('lesson-editor')?.scrollIntoView({behavior:'smooth'});
  };
  const save=async(e:React.FormEvent)=>{
    e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');
    try{
      const body=new FormData();Object.entries(form).forEach(([key,value])=>body.append(key,String(value)));
      body.append('videosJson',JSON.stringify(videos));body.append('quizJson',JSON.stringify(quiz));body.append('relatedPaperIds',JSON.stringify(related));body.append('keepResourceIds',JSON.stringify(resources.map(r=>r.id)));
      if(editing)body.append('revision',String(editing.revision));files.forEach(f=>body.append('pdfFiles',f));
      const result=editing?await api.updateCourse(editing._id,body):await api.createCourse(body);
      load();
      reset();setMessage(result.course.status==='draft'?'Draft saved. It is hidden from students.':'Lesson published. Students can find it under its subject and topic.');window.dispatchEvent(new Event('mindmaze_courses_updated'));
    }catch(e:any){setError(e.message);}finally{setBusy(false);}
  };
  const remove=async(lesson:Lesson)=>{if(!window.confirm(`Delete “${lesson.title}” and its lesson progress?`))return;setBusy(true);setError('');try{await api.deleteCourse(lesson._id);load();if(editing?._id===lesson._id)reset();setMessage('Lesson deleted.');window.dispatchEvent(new Event('mindmaze_courses_updated'));}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  const changeQuestion=(i:number,patch:Partial<Question>)=>setQuiz(prev=>prev.map((q,j)=>j===i?{...q,...patch}:q));
  const visible=lessons.filter(l=>(!filterSubject||l.subject===filterSubject)&&(!filterStatus||l.status===filterStatus)&&[l.title,l.topic,l.subject].join(' ').toLowerCase().includes(search.trim().toLowerCase()));
  return <section className="learning-area space-y-6">
    <header className={panel}><h2 className="text-xl font-bold text-white">Manage courses & lessons</h2><p className="text-sm text-slate-400">Choose a subject and topic, add a lesson, then attach videos, notes and practice questions.</p></header>
    {message&&<p role="status" className="text-emerald-300">{message}</p>}{error&&<p role="alert" className="text-rose-300">{error}</p>}
    {preview&&<div className={panel}><button className={button} onClick={()=>setPreview(null)}>Close student preview</button><LessonView key={preview._id} lesson={preview} preview onProgress={()=>{}}/></div>}
    <form id="lesson-editor" onSubmit={save} className={panel}>
      <h3 className="text-lg font-bold text-white">{editing?'Edit lesson':'Create a lesson'}</h3>
      <fieldset disabled={busy} className="space-y-5">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <label className="text-sm text-slate-300">Subject<select className={control+' mt-1'} value={form.subject} onChange={e=>setForm(f=>({...f,subject:e.target.value,topic:''}))}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label>
          <label className="text-sm text-slate-300">Topic<input required list="lesson-topics" className={control+' mt-1'} value={form.topic} placeholder="Choose or enter a new topic" onChange={e=>{const value=e.target.value,match=topicChoices.find(l=>l.subject===form.subject&&l.topic===value);setForm(f=>({...f,topic:value,...(match?{topicOrder:match.topicOrder}:{})}));}}/><datalist id="lesson-topics">{[...new Set(topicChoices.filter(l=>l.subject===form.subject).map(l=>l.topic))].map(t=><option key={t} value={t}/>)}</datalist></label>
          <label className="text-sm text-slate-300">Target stream<select className={control+' mt-1'} value={form.stream} onChange={e=>setForm(f=>({...f,stream:e.target.value}))}>{['Both','Maths','Bio','Physical Science','Biological Science','Non-stream'].map(s=><option key={s} value={s}>{s==='Both'?'Maths and Bio':s}</option>)}</select></label>
          <label className="text-sm text-slate-300">Topic order<input type="number" min="0" max="1000" required className={control+' mt-1'} value={form.topicOrder} onChange={e=>setForm(f=>({...f,topicOrder:Number(e.target.value)}))}/></label>
          <label className="text-sm text-slate-300">Lesson order<input type="number" min="0" max="1000" required className={control+' mt-1'} value={form.lessonOrder} onChange={e=>setForm(f=>({...f,lessonOrder:Number(e.target.value)}))}/></label>
          <label className="text-sm text-slate-300">Study time (minutes)<input type="number" min="1" max="600" required className={control+' mt-1'} value={form.estimatedMinutes} onChange={e=>setForm(f=>({...f,estimatedMinutes:Number(e.target.value)}))}/></label>
          <label className="text-sm text-slate-300">Language<select className={control+' mt-1'} value={form.medium} onChange={e=>setForm(f=>({...f,medium:e.target.value}))}>{['English','Sinhala','Tamil'].map(s=><option key={s}>{s}</option>)}</select></label>
          <label className="text-sm text-slate-300">Syllabus<select className={control+' mt-1'} value={form.syllabus} onChange={e=>setForm(f=>({...f,syllabus:e.target.value}))}><option value="current">Current syllabus</option><option value="old">Old syllabus</option></select></label>
          <label className="text-sm text-slate-300">Visibility<select className={control+' mt-1'} value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}><option value="draft">Draft — hidden from students</option><option value="published">Published</option></select></label>
        </div>
        <label className="block text-sm text-slate-300">Lesson title<input required className={control+' mt-1'} value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></label>
        <label className="block text-sm text-slate-300">What students will learn<textarea required rows={3} className={control+' mt-1'} value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></label>
        <section className="space-y-3"><h4 className="font-bold text-white">Video lessons</h4>{videos.map((v,i)=><div key={i} className="grid sm:grid-cols-[1fr_2fr_auto] gap-2"><input aria-label={`Video ${i+1} title`} required placeholder="Video title" className={control} value={v.title} onChange={e=>setVideos(prev=>prev.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/><input aria-label={`Video ${i+1} URL`} required type="url" placeholder="https://www.youtube.com/watch?v=…" className={control} value={v.url} onChange={e=>setVideos(prev=>prev.map((x,j)=>j===i?{...x,url:e.target.value}:x))}/><button type="button" className="text-rose-300 text-sm" onClick={()=>setVideos(prev=>prev.filter((_,j)=>j!==i))}>Remove video</button></div>)}<button type="button" className="text-cyan-300 text-sm" disabled={videos.length>=20} onClick={()=>setVideos(prev=>[...prev,{title:'',url:''}])}>+ Add video</button></section>
        <section className="space-y-3"><h4 className="font-bold text-white">PDF notes</h4>{resources.map(r=><div key={r.id} className="flex gap-3 justify-between text-sm text-slate-300"><span>{r.title}</span><button type="button" className="text-rose-300" onClick={()=>setResources(prev=>prev.filter(x=>x.id!==r.id))}>Remove PDF</button></div>)}<label className="block text-sm text-slate-300">Add PDFs (up to 8 per save, 25 MiB each)<input key={fileKey} type="file" multiple accept="application/pdf,.pdf" className="block mt-2 w-full" onChange={e=>{const selected=Array.from(e.target.files||[]);if(selected.length>8||selected.some(f=>f.size>25*1024*1024)){setError('Choose up to 8 PDFs, each no larger than 25 MiB.');e.target.value='';setFiles([]);return;}setFiles(selected);setError('');}}/></label><p className="text-xs text-slate-400">Your storage account may have a lower file-size limit. Existing PDFs stay attached unless removed.</p></section>
        <section className="space-y-4"><h4 className="font-bold text-white">Practice quiz ({quiz.length} questions)</h4>{quiz.map((q,i)=><div key={i} className="rounded-xl bg-slate-800 p-4 space-y-3"><label className="block text-sm text-slate-300">Question {i+1}<textarea required className={control+' mt-1'} value={q.questionText} onChange={e=>changeQuestion(i,{questionText:e.target.value})}/></label><div className="grid sm:grid-cols-2 gap-2">{q.options.map((o,j)=><label key={j} className="text-xs text-slate-400">Answer {j+1}<input required className={control+' mt-1'} value={o} onChange={e=>changeQuestion(i,{options:q.options.map((x,k)=>k===j?e.target.value:x)})}/></label>)}</div><div className="flex flex-wrap gap-3"><button type="button" disabled={q.options.length>=6} className="text-cyan-300 text-sm" onClick={()=>changeQuestion(i,{options:[...q.options,'']})}>+ Add answer</button><button type="button" disabled={q.options.length<=2} className="text-slate-300 text-sm" onClick={()=>changeQuestion(i,{options:q.options.slice(0,-1),correctOptionIndex:Math.min(q.correctOptionIndex,q.options.length-2)})}>Remove last answer</button></div><label className="block text-sm text-slate-300">Correct answer<select className={control+' mt-1'} value={q.correctOptionIndex} onChange={e=>changeQuestion(i,{correctOptionIndex:Number(e.target.value)})}>{q.options.map((_,j)=><option key={j} value={j}>Answer {j+1}</option>)}</select></label><label className="block text-sm text-slate-300">Explanation<textarea className={control+' mt-1'} value={q.explanation} onChange={e=>changeQuestion(i,{explanation:e.target.value})}/></label><button type="button" className="text-rose-300 text-sm" onClick={()=>setQuiz(prev=>prev.filter((_,j)=>j!==i))}>Remove question</button></div>)}<button type="button" className="text-cyan-300 text-sm" disabled={quiz.length>=100} onClick={()=>setQuiz(prev=>[...prev,{questionText:'',options:['',''],correctOptionIndex:0,explanation:''}])}>+ Add quiz question</button></section>
        <fieldset className="space-y-2"><legend className="font-bold text-white mb-2">Related past papers</legend><label className="block text-sm text-slate-300">Search related papers<input className={control} type="search" value={paperSearch} onChange={e=>setPaperSearch(e.target.value)}/></label><label className="flex gap-2 text-sm text-slate-300"><input type="checkbox" checked={selectedPapersOnly} onChange={e=>setSelectedPapersOnly(e.target.checked)}/>Show selected papers ({related.length})</label><Pagination {...papersPage.pagination} label="Related papers"/>{papersPage.error&&<p role="alert">{papersPage.error} <button type="button" onClick={papersPage.reload}>Retry</button></p>}<div className="max-h-44 overflow-y-auto space-y-2">{papers.map(p=><label key={p.id} className="flex gap-2 text-sm text-slate-300"><input type="checkbox" checked={related.includes(p.id)} onChange={e=>setRelated(prev=>e.target.checked?[...prev,p.id]:prev.filter(id=>id!==p.id))}/>{p.title}</label>)}{papersPage.loading?<p role="status">Loading papers…</p>:!papers.length&&!papersPage.error&&<p className="text-sm text-slate-400">No matching papers.</p>}</div></fieldset>
        <div className="flex flex-wrap gap-3"><button type="submit" className={button}>{busy?'Saving lesson…':form.status==='draft'?'Save draft':editing?'Save and publish changes':'Publish lesson'}</button>{editing&&<button type="button" className="text-slate-300" onClick={reset}>Cancel editing</button>}</div>
      </fieldset>
    </form>
    <section className={panel}><h3 className="font-bold text-white text-lg">All lessons ({lessonsPage.pagination.total})</h3><div className="grid sm:grid-cols-3 gap-3"><input aria-label="Search lessons" type="search" className={control} placeholder="Search title or topic" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter lessons by subject" className={control} value={filterSubject} onChange={e=>setFilterSubject(e.target.value)}><option value="">All subjects</option>{subjects.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter lessons by visibility" className={control} value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option></select></div><Pagination {...lessonsPage.pagination} label="Admin lessons"/>{lessonsPage.error&&<p role="alert" className="text-rose-300">{lessonsPage.error} <button onClick={load}>Retry</button></p>}{loading?<p className="text-slate-400">Loading lessons…</p>:visible.length?visible.map(l=><article key={l._id} className="rounded-xl bg-slate-800 p-4 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs text-cyan-300">{l.subject} / {l.topic} · Lesson {l.lessonOrder} · {l.status}</p><h4 className="font-bold text-white mt-1">{l.title}</h4></div><div className="flex gap-4 text-sm"><button disabled={busy} type="button" className="text-cyan-300" onClick={()=>edit(l)}>Edit</button><button disabled={busy} type="button" className="text-slate-300" onClick={()=>{setPreview(l);document.getElementById('lesson-editor')?.parentElement?.scrollIntoView({behavior:'smooth'});}}>Preview</button><button disabled={busy} type="button" className="text-rose-300" onClick={()=>remove(l)}>Delete</button></div></article>):<p className="text-slate-400">No matching lessons. Create a lesson above.</p>}<button type="button" onClick={load} className="text-sm text-cyan-300">Refresh lessons</button></section>
  </section>;
};
